### ISSUE TITLE
Minecraft Chat 

### ISSUE THREAD

**Issue by MysticCity** [xXBuilderBXx/MC-Bot#6]
PLS add an Option to Sync the Minecraft Server Chat with Discord
And Integrade alle Perms & Commands on your Bot.

So Admin/ User can Talk in Discord and see ingame
and 
can talk ingame and see on Discord

+

Admin can Use Commands in Discord and do9nt need logged on the Server

**Comment by xXBuilderBXx** [comment]
There are already plugins out there that do this kind of thing.
